### ISSUE TITLE
Setting Dimmer Level to 99% returns a second event at 100%

### ISSUE THREAD

**Issue by Botched1** [jvmahon/HubitatCustom#3]
When I do a setLevel at 99% I get two events. One with value=99, and one with value=100 (even though the text descriptions still says 99).

Also, the 2nd event type is PHYSICAL, even though the setLevel was done from the hub. The 1st event shows the correct type of DIGITAL though.

This is from a single setLevel=99 command:
![image](https://user-images.githubusercontent.com/19985320/103390025-d2cce700-4ad7-11eb-8822-d3551969ed17.png)

**Comment by jvmahon** [comment]
What type of device is this?
I've fixed the descriptive text in 0.0.3

I know why this is happening, but need to give some thought as to how to fix. It relates to a design decision intended to speed up the Hubitat system but it can cause duplicate messages in some devices, depending on if they automatically send a report every time they transition, or if you have to request the report. I'll give this some more thought - I should be able to eliminate the extra report.

**Comment by jvmahon** [comment]
I have a beta 0.0.4 which I think fixes the duplicate events. If you want to give it a try for your switch, download the drivers from the "beta 0.0.4" branch on github. I'll test for a bit on my system, but if I don't notice any errors will then integrated it into the main code.

**Comment by Botched1** [comment]
On 0.0.4 when sending a setLevel of 99 to any new style GE/Jasco/Honeywell device I see this:
![image](https://user-images.githubusercontent.com/19985320/103415570-5e7e5c00-4b48-11eb-92e9-89836305700d.png)

**Comment by jvmahon** [comment]
As an FYI, I probably won't try to fix the "second event" issue until 2.2.5 is released. They are going to add the multilevel Version 4 class in that release (which is implemented in your switch) -- the v4 class gives additional information in the reports originating from the switch -- in particular, it provies duration and target value information. I think I can use these to filter out duplicate "physical" events by checking if the targetValue matches a "digital" event that occurred within a duration specified in the duration data.

**Comment by Botched1** [comment]
No worries - your driver, your choice.

This is the reason most drivers don't make an event on the digital command though, and only make it on the report event. On those when the digital command is done they just set a "digital" flag in the hub, then when the report comes in, if the flag is set the event is digital if not it is physical.

No need to dedupe ever when you only register events on the reports.

**Comment by Botched1** [comment]
Still don't think that the level should ever read 100% though, as that isn't a valid/correct value for level on a zwave device.

**Comment by jvmahon** [comment]
Understood about the 100% - though I did this intentionally as the "average consumer" rather than "average person who understands Z-wave" likely thinks about devices going up to 100% when fully on (its just an odd z-wave decision to go from 1-99).  You could look at it as each z-wave digit being equal to 1.01% so a value of 99 = 100%.

What's happening is that, if you send 100% to the Z-wave device, the driver sends a 99 value (actually, either 99 or 100 result in a 99 being sent), but sends a 100% in the sendEvent to indicate fully-on. Similarly, if you receive a 99 in a report from a device, which is z-wave's full-on value, I treat it as 100%, so the scale ends up being 100%, 98%, 97%...1%, 0 and skips the 99.  In other words, I've chosen to have a clear indication of fully-on using the standard 100%.

There are a number of other driver implementations that take this approach. If its bothersome to people, I could put in a preference to turn this on/off (i.e., s "Map Z-wave 99 value to 100%" preference). I'm on a wait-and-see on this one for now - there are a lot of other features I want to add first.

**Comment by Botched1** [comment]
Understood, and like I said it is your driver so your choice.

All of my automations are set to send 99%, so that feature would definitely make me not use this driver as I don't like setting 99 and it returning 100. That, and I like my drivers to match the in-box behavior (which follows the protocol spec of 0-99).

But I doubt most other users would really care, and may even prefer it going to 100. So no worries.

**Comment by jvmahon** [comment]
FYI - I just found a typo in the code which I think was causing the double-event problem in your first post. I'm preparing an updated version that will be released at same time as Hubitat 2.2.5 (which just went into beta). The update will require Hubitat 2.2.5 (there are some bugs in current Hubitat code that was causing me some problems, but I understand they are fixed in 2.2.5, so I'm going to require that). If you are a beta-tester for 2.2.5, I can also send you a link to the beta-test version of the updated driver (figure it will be Saturday or Sunday before I have that ready).

**Comment by jvmahon** [comment]
I think this is fixed in the 0.1.1 version. Reopen if problems persist.
